CREATE TABLE Shows (ShowID INT PRIMARY KEY, Title VARCHAR(100), SeatsAvailable INT);
CREATE TABLE Users (UserID INT PRIMARY KEY, Name VARCHAR(100));
CREATE TABLE Tickets (TicketID INT PRIMARY KEY, ShowID INT, UserID INT, SeatNumber VARCHAR(10));