CREATE TABLE Events (EventID INT PRIMARY KEY, EventName VARCHAR(100), Capacity INT);
CREATE TABLE Participants (PartID INT PRIMARY KEY, Name VARCHAR(100));
CREATE TABLE Bookings (BookingID INT PRIMARY KEY, EventID INT, PartID INT);