-- ==========================================
-- 10 Complex Queries for Hospital Management
-- ==========================================

-- 1. Retrieve all patients who have an appointment in the next 7 days (JOIN + Date Function)
SELECT p.FirstName, p.LastName, a.AppointmentDate, d.Specialization
FROM Patients p
JOIN Appointments a ON p.PatientID = a.PatientID
JOIN Doctors d ON a.DoctorID = d.DoctorID
WHERE a.AppointmentDate BETWEEN GETDATE() AND DATEADD(day, 7, GETDATE());

-- 2. Find the total revenue generated by each doctor (JOIN + GROUP BY + Aggregation)
SELECT d.FirstName, d.LastName, ISNULL(SUM(b.TotalAmount), 0) AS TotalRevenue
FROM Doctors d
LEFT JOIN Appointments a ON d.DoctorID = a.DoctorID
LEFT JOIN Treatments t ON a.AppointmentID = t.AppointmentID
LEFT JOIN Billing b ON t.TreatmentID = b.TreatmentID AND b.PaymentStatus = 'Paid'
GROUP BY d.FirstName, d.LastName
ORDER BY TotalRevenue DESC;

-- 3. Find patients who have never had an appointment (Subquery)
SELECT FirstName, LastName, ContactNumber
FROM Patients
WHERE PatientID NOT IN (SELECT PatientID FROM Appointments);

-- 4. Get the details of the most expensive treatment (Subquery + MAX)
SELECT t.Diagnosis, b.TotalAmount, p.FirstName AS PatientName
FROM Treatments t
JOIN Billing b ON t.TreatmentID = b.TreatmentID
JOIN Appointments a ON t.AppointmentID = a.AppointmentID
JOIN Patients p ON a.PatientID = p.PatientID
WHERE b.TotalAmount = (SELECT MAX(TotalAmount) FROM Billing);

-- 5. List all doctors and the count of their completed appointments (LEFT JOIN + GROUP BY)
SELECT d.FirstName, d.LastName, COUNT(a.AppointmentID) AS CompletedAppointments
FROM Doctors d
LEFT JOIN Appointments a ON d.DoctorID = a.DoctorID AND a.Status = 'Completed'
GROUP BY d.FirstName, d.LastName;

-- 6. Find patients with multiple appointments (HAVING clause)
SELECT p.PatientID, p.FirstName, p.LastName, COUNT(a.AppointmentID) AS TotalAppointments
FROM Patients p
JOIN Appointments a ON p.PatientID = a.PatientID
GROUP BY p.PatientID, p.FirstName, p.LastName
HAVING COUNT(a.AppointmentID) > 1;

-- 7. View all pending bills with patient and doctor details (Multiple Joins)
SELECT p.FirstName AS PatientName, d.FirstName AS DoctorName, t.Diagnosis, b.TotalAmount, b.BillingDate
FROM Billing b
JOIN Treatments t ON b.TreatmentID = t.TreatmentID
JOIN Appointments a ON t.AppointmentID = a.AppointmentID
JOIN Patients p ON a.PatientID = p.PatientID
JOIN Doctors d ON a.DoctorID = d.DoctorID
WHERE b.PaymentStatus = 'Pending';

-- 8. Use Scalar Function to get total paid by a specific patient (Function execution)
-- Assuming PatientID = 1
SELECT dbo.fn_GetTotalPaidByPatient(1) AS TotalPaidByPatient1;

-- 9. Correlated subquery to find treatments that cost more than the average treatment cost
SELECT t.Diagnosis, b.TotalAmount
FROM Treatments t
JOIN Billing b ON t.TreatmentID = b.TreatmentID
WHERE b.TotalAmount > (
    SELECT AVG(TotalAmount) 
    FROM Billing
);

-- 10. Display a summary of all operations logged today (Filtering on AuditLogs)
SELECT TableName, Operation, COUNT(*) AS OperationCount
FROM AuditLogs
WHERE CAST(LogDate AS DATE) = CAST(GETDATE() AS DATE)
GROUP BY TableName, Operation;
