CREATE TABLE Guests (GuestID INT PRIMARY KEY, Name VARCHAR(100));
CREATE TABLE Rooms (RoomID INT PRIMARY KEY, RoomType VARCHAR(50), Price DECIMAL(10,2), IsAvailable BIT);
CREATE TABLE Reservations (ResID INT PRIMARY KEY, GuestID INT, RoomID INT, CheckIn DATE, CheckOut DATE);
CREATE TABLE Billing (BillID INT PRIMARY KEY, ResID INT, Amount DECIMAL(10,2), Status VARCHAR(20));