-- DDL for Bank Management
CREATE TABLE Customers (CustomerID INT PRIMARY KEY, Name VARCHAR(100), KYC_Status VARCHAR(20));
CREATE TABLE Accounts (AccountID INT PRIMARY KEY, CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID), Balance DECIMAL(15,2));
CREATE TABLE Transactions (TxnID INT PRIMARY KEY, AccountID INT FOREIGN KEY REFERENCES Accounts(AccountID), Amount DECIMAL(15,2), TxnType VARCHAR(10), TxnDate DATETIME DEFAULT GETDATE());
CREATE TABLE AuditLogs (LogID INT PRIMARY KEY, TableName VARCHAR(50), Operation VARCHAR(50), LogDate DATETIME DEFAULT GETDATE());
