CREATE TABLE Properties (PropID INT PRIMARY KEY, Address VARCHAR(200), Price DECIMAL(15,2), Status VARCHAR(20));
CREATE TABLE Clients (ClientID INT PRIMARY KEY, Name VARCHAR(100), Role VARCHAR(20));
CREATE TABLE Transactions (TxnID INT PRIMARY KEY, PropID INT, BuyerID INT, SellerID INT, TxnDate DATE);